import subprocess
import os
from pathlib import Path

Import('env', 'arch', 'common', 'messaging', 'visionipc', 'replay_lib', 'cereal')

qt_env = env.Clone()

# Configure build directory
build_dir = Dir('#build').abspath
qt_env['QT_MOCFROMHDIR'] = os.path.join(build_dir, 'moc')
qt_env['QT_MOCFROMCXXDIR'] = os.path.join(build_dir, 'moc')

qt_env["CPPPATH"] += ["#"]
qt_modules = ["Widgets", "Gui", "Core", "Concurrent", "DBus", "Svg", "OpenGL", "OpenGLWidgets", "PrintSupport", "Charts", "SerialBus"]

qt_libs = []
qt_host_bins = ""
qt_root = os.environ.get("CABANA_QT_ROOT")

if qt_root:
    qt_install_prefix = os.path.join(qt_root, "usr")
    qt_install_headers = os.path.join(qt_install_prefix, "include", "x86_64-linux-gnu", "qt6")
    qt_host_bins = os.path.join(qt_install_prefix, "lib", "qt6", "libexec")

    qt_env["QTDIR"] = qt_install_prefix
    qt_dirs = [qt_install_headers]
    qt_dirs += [f"{qt_install_headers}/Qt{m}" for m in qt_modules]
    qt_libs = [f"Qt6{m}" for m in qt_modules]
    qt_libs += ["GL"]

    qt_lib_path = os.path.join(qt_install_prefix, "lib", "x86_64-linux-gnu")
    qt_env.Append(LIBPATH=[qt_lib_path])
    qt_env.AppendENVPath("PATH", qt_host_bins)
    qt_env.AppendENVPath("LD_LIBRARY_PATH", qt_lib_path)
elif arch == "Darwin":
    brew_prefix = subprocess.check_output(['brew', '--prefix'], encoding='utf8').strip()
    qt_env['QTDIR'] = f"{brew_prefix}/opt/qt@6"
    qt_dirs = [os.path.join(qt_env['QTDIR'], "include")]
    qt_dirs += [f"{qt_env['QTDIR']}/include/Qt{m}" for m in qt_modules]
    qt_env["LINKFLAGS"] += ["-F" + os.path.join(qt_env['QTDIR'], "lib")]
    qt_env["FRAMEWORKS"] += [f"Qt{m}" for m in qt_modules] + ["OpenGL"]
    qt_env.AppendENVPath('PATH', os.path.join(qt_env['QTDIR'], "bin"))
    qt_host_bins = os.path.join(qt_env['QTDIR'], "bin")
else:
    # Use qmake6 to find paths
    qt_install_prefix = subprocess.check_output(['qmake6', '-query', 'QT_INSTALL_PREFIX'], encoding='utf8').strip()
    qt_install_headers = subprocess.check_output(['qmake6', '-query', 'QT_INSTALL_HEADERS'], encoding='utf8').strip()
    qt_host_bins = subprocess.check_output(['qmake6', '-query', 'QT_HOST_BINS'], encoding='utf8').strip()

    # Validation for Ubuntu/Debian 'libexec' vs 'bin'
    if not os.path.exists(os.path.join(qt_host_bins, 'moc')):
        if os.path.exists('/usr/lib/qt6/libexec/moc'):
            qt_host_bins = '/usr/lib/qt6/libexec'

    qt_env['QTDIR'] = qt_install_prefix
    qt_dirs = [qt_install_headers]

    # Handle Private QPA headers if necessary
    qt_gui_path = os.path.join(qt_install_headers, "QtGui")
    if os.path.exists(qt_gui_path):
        qt_gui_dirs = [d for d in os.listdir(qt_gui_path) if os.path.isdir(os.path.join(qt_gui_path, d))]
        qt_dirs += [f"{qt_install_headers}/QtGui/{qt_gui_dirs[0]}/QtGui"] if qt_gui_dirs else []

    qt_dirs += [f"{qt_install_headers}/Qt{m}" for m in qt_modules]
    qt_libs = [f"Qt6{m}" for m in qt_modules]

    if arch == "larch64":
        qt_libs += ["GLESv2", "wayland-client"]
    else:
        qt_libs += ["GL"]

# Load the tool first, then immediately overwrite its broken path assumptions
qt_env['QT3DIR'] = qt_env['QTDIR']
qt_env.Tool('qt3')

# Define absolute paths to binaries
moc_bin = os.path.join(qt_host_bins, 'moc')

uic_bin = os.path.join(qt_host_bins, 'uic')
rcc_bin = os.path.join(qt_host_bins, 'rcc')

# Replace the command templates that SCons uses internally
qt_env.Replace(
    QT_MOC = moc_bin,
    QT_UIC = uic_bin,
    RCC = rcc_bin,
    MOC = moc_bin,
    UIC = uic_bin,
    # Overwrite the command strings to ensure they don't prepend $QTDIR/bin
   QT3_MOC = moc_bin,
)

qt_env['CPPPATH'] += qt_dirs + ["#src", "#src/widgets", "#src/streams", "#src/dbc", "#src/chart", "#src/tools", "#src/utils"]

qt_flags = [
    "-D_REENTRANT", "-DQT_NO_DEBUG", "-DQT_WIDGETS_LIB", "-DQT_GUI_LIB",
    "-DQT_CORE_LIB", "-DQT_SVG_LIB", "-DQT_MESSAGELOGCONTEXT",
    "-Wno-deprecated-enum-enum-conversion",
]
qt_env['CXXFLAGS'] += qt_flags

base_frameworks = qt_env.get('FRAMEWORKS', [])
base_libs = [common, messaging, cereal, visionipc, 'm', 'ssl', 'crypto', 'pthread'] + qt_libs

if arch == "Darwin":
    base_frameworks += ['OpenCL', 'QtCharts', 'QtSerialBus']
else:
    base_libs += ['OpenCL', 'Qt6Charts', 'Qt6SerialBus']

cabana_env = qt_env.Clone()
cabana_env.VariantDir('#build', '.', duplicate=0)

# Build assets using the verified RCC path
assets = "#build/assets/assets.cc"
assets_src = "#/resources.qrc"
cabana_env.Command(assets, assets_src, f"$RCC $SOURCES -o $TARGET")
cabana_env.Depends(assets, [assets_src] + Glob('assets/*.svg'))

src_files = Glob('#src/*.cc') + Glob('#src/*/*.cc') + Glob('#src/*/*/*.cc') + Glob('#src/*/*/*/*.cc')
src_file_strings = ['#build/' + str(f) for f in src_files if f != 'main.cc']

cabana_libs = [cereal, messaging, visionipc, replay_lib, 'avutil', 'avcodec', 'avformat', 'swscale','bz2', 'zstd', 'curl', 'usb-1.0'] + base_libs

cabana_lib = cabana_env.Library(
    "#build/cabana_lib",
    src_file_strings,
    LIBS=cabana_libs,
    FRAMEWORKS=base_frameworks,
)
cabana_env.Program('#cabana', ['#build/main.cc', cabana_lib, assets], LIBS=cabana_libs, FRAMEWORKS=base_frameworks)
